"""
src/exporter/report_generator.py
================================
Compiles structural markdown reports for ingestion summaries, failures,
deduplication events, and system telemetry metrics.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Compiles and writes structured execution reports to markdown files.
    """

    @staticmethod
    def generate_summary_report(
        completed_count: int,
        failed_count: int,
        retry_count: int,
        duplicate_count: int,
        filepath: str
    ) -> None:
        """Generates ingestion overall metrics summary."""
        path = Path(filepath)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            
            content = f"""# Contact Enrichment Ingestion Summary Report

Generated at: {datetime.now(timezone.utc).isoformat()} Z

## Processing Metrics Overview
| Metric | Count |
| :--- | :--- |
| Completed / Enriched Records | {completed_count} |
| Failed Ingestion Records | {failed_count} |
| Pending Retry Records | {retry_count} |
| Duplicates Merged | {duplicate_count} |
| **Total Ingested** | {completed_count + failed_count + retry_count + duplicate_count} |

---
*Generated by the Contact Enrichment Engine Persistence & Export Engine.*
"""
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"[ReportGenerator] Saved summary report to {filepath}")
        except Exception as e:
            logger.error(f"[ReportGenerator] Error generating summary report: {e}")

    @staticmethod
    def generate_failed_report(failed_records: List[Dict[str, Any]], filepath: str) -> None:
        """Generates details of all failed ingestion rows."""
        path = Path(filepath)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            
            rows_md = []
            if failed_records:
                for idx, r in enumerate(failed_records):
                    npi = r.get("npi") or "N/A"
                    company = r.get("company_name") or r.get("business_name") or "N/A"
                    web = r.get("website") or "N/A"
                    err = r.get("error_message") or "Unknown execution error"
                    rows_md.append(f"| {idx+1} | {npi} | {company} | {web} | {err} |")
            else:
                rows_md.append("| None | - | - | - | - |")
                
            content = f"""# Failed Records Report

The following records failed processing and could not be successfully crawled or validated:

| Index | NPI | Company Name | Target Website | Failure Reason |
| :--- | :--- | :--- | :--- | :--- |
{"\n".join(rows_md)}
"""
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"[ReportGenerator] Saved failed records report to {filepath}")
        except Exception as e:
            logger.error(f"[ReportGenerator] Error generating failed report: {e}")

    @staticmethod
    def generate_duplicate_report(duplicate_records: List[Dict[str, Any]], filepath: str) -> None:
        """Generates list of duplicate-merged contacts."""
        path = Path(filepath)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            
            rows_md = []
            if duplicate_records:
                for idx, r in enumerate(duplicate_records):
                    npi = r.get("npi") or "N/A"
                    company = r.get("company_name") or r.get("business_name") or "N/A"
                    web = r.get("website") or r.get("official_website") or "N/A"
                    resolution = r.get("resolution", "Merged list collections, updated fields and scores")
                    rows_md.append(f"| {idx+1} | {npi} | {company} | {web} | {resolution} |")
            else:
                rows_md.append("| None | - | - | - |")

            content = f"""# Duplicate Detection & Merging Report

The following records were identified as duplicates and merged at database or validation levels:

| Index | NPI | Company Name | Website | Resolution |
| :--- | :--- | :--- | :--- | :--- |
{"\n".join(rows_md)}
"""
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"[ReportGenerator] Saved duplicate report to {filepath}")
        except Exception as e:
            logger.error(f"[ReportGenerator] Error generating duplicate report: {e}")

    @staticmethod
    def generate_statistics_report(
        db_metrics_file: str = "logs/database_metrics.json",
        val_metrics_file: str = "logs/validation_metrics.json",
        ai_metrics_file: str = "logs/ai_metrics.json",
        filepath: str = "data/export/statistics_report.md"
    ) -> None:
        """Gathers metrics JSON logs and compiles system-wide telemetry stats."""
        path = Path(filepath)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            
            # Helper loads file or defaults
            def load_json(fp: str) -> Dict[str, Any]:
                p = Path(fp)
                if p.exists():
                    try:
                        with open(p, "r") as f:
                            return json.load(f)
                    except Exception:
                        pass
                return {}

            db = load_json(db_metrics_file)
            val = load_json(val_metrics_file)
            ai = load_json(ai_metrics_file)

            db_counts = db.get("counts", {})
            db_perf = db.get("performance", {})
            val_counts = val.get("counts", {})
            val_perf = val.get("performance", {})
            ai_counts = ai.get("counts", {})
            ai_perf = ai.get("performance", {})

            content = f"""# Telemetry & Performance Statistics Report

Complete system performance diagnostics across database persistence, validation, and AI enrichment layers.

## Database Ingestion Diagnostics
- **Total Inserts**: {db_counts.get("total_inserts", 0)}
- **Total Updates / Merges**: {db_counts.get("total_updates", 0)}
- **Database Write Speed**:
  - Inserts/sec: {db_perf.get("average_insert_speed_records_per_sec", 0.0)}
  - Updates/sec: {db_perf.get("average_update_speed_records_per_sec", 0.0)}
- **Failed Writes Count**: {db_counts.get("failed_writes", 0)}
- **Write Retries Count**: {db_counts.get("retries", 0)}
- **Total DB Session Latency**: {db_perf.get("total_write_time_seconds", 0.0)}s

## Validation Diagnostics
- **Validated Emails**: {val_counts.get("validated_emails", 0)}
- **Validated Phone Numbers**: {val_counts.get("validated_phones", 0)}
- **Duplicates Removed**: {val_counts.get("duplicates_removed", 0)}
- **Average Validation Latency**: {val_perf.get("average_validation_time_seconds", 0.0)}s
- **Total Validation Latency**: {val_perf.get("total_validation_time", 0.0)}s

## AI Enrichment Diagnostics
- **AI API Calls**: {ai_counts.get("ai_calls", 0)}
- **AI Calls Avoided (Cache/Scraper hit)**: {ai_counts.get("ai_avoided", 0)}
- **Total Tokens Consumed**: {ai_counts.get("total_tokens", 0)}
- **Average AI Latency**: {ai_perf.get("average_enrichment_time_seconds", 0.0)}s
- **Total AI Latency**: {ai_perf.get("total_enrichment_time", 0.0)}s
"""
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"[ReportGenerator] Saved statistics report to {filepath}")
        except Exception as e:
            logger.error(f"[ReportGenerator] Error generating statistics report: {e}")
